USE AMAZON;

SELECT *
FROM USERS;

SELECT ID, NAME
FROM USERS
ORDER BY NAME ASC;

SELECT *
FROM USERS
WHERE EMAIL LIKE '%@GMAIL.COM';

SELECT *
FROM USERS
WHERE DATA_DE_NASCIMENTO > '2000-12-31';

INSERT INTO USERS (NAME, EMAIL, DATA_DE_NASCIMENTO)
VALUES
('ANA SILVA', 'ANA.SILVA@GMAIL.COM', '2001-03-15'),
('ARTHUR COSTA', 'ARTHUR.COSTA@OUTLOOK.COM', '2002-07-22'),
('AMANDA LIMA', 'AMANDA.LIMA@GMAIL.COM', '2003-11-09'),
('ALEX SOUZA', 'ALEX.SOUZA@YAHOO.COM', '2004-01-30'),
('ALINE PEREIRA', 'ALINE.PEREIRA@GMAIL.COM', '2005-06-18');

SELECT *
FROM CATEGORIES;

SELECT *
FROM PRODUCTS
WHERE PRICE > 100;

SELECT *
FROM PRODUCTS
WHERE PRICE BETWEEN 50 AND 200;

SELECT *
FROM PRODUCTS
ORDER BY PRICE DESC;

SELECT *
FROM PRODUCTS
WHERE CATEGORY_ID IN (1, 2, 3);

SELECT *
FROM PRODUCTS
WHERE NAME LIKE 'A%';

INSERT INTO PRODUCTS (NAME, PRICE, CATEGORY_ID)
VALUES
('ABAJUR LED', 120.00, 1),
('ADAPTADOR USB', 45.00, 2),
('ALMOFADA DECORATIVA', 80.00, 3),
('ASPIRADOR DE PO', 350.00, 4),
('APARELHO DE SOM', 900.00, 5);

SELECT *
FROM ORDERS;

SELECT *
FROM ORDERS
WHERE USER_ID IN (1, 5, 10);

SELECT *
FROM ORDERS
ORDER BY ORDER_DATE DESC;

SELECT *
FROM ORDER_ITEMS
WHERE QUANTITY > 1;

SELECT *
FROM ORDER_ITEMS
WHERE PRODUCT_ID IN (3, 7, 9);

SELECT *
FROM REVIEWS
WHERE RATING >= 4;

SELECT *
FROM REVIEWS
WHERE REVIEW_DATE BETWEEN '2023-01-01' AND '2023-12-31';

SELECT *
FROM REVIEWS
ORDER BY RATING DESC;

SELECT *
FROM PRODUCTS
WHERE ID NOT IN (
    SELECT PRODUCT_ID
    FROM REVIEWS
);

SELECT *
FROM USERS
WHERE ID IN (
    SELECT USER_ID
    FROM ORDERS
);