USE DB_JOAO_VICTOR;

CREATE TABLE BANK (
    BANK_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    BANK_NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ENGINE=INNODB;
);

CREATE TABLE CLIENT (
 CLIENT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 BANK_ID BIGINT UNSIGNED NOT NULL,
 CLIENT_NAME VARCHAR(100) NOT NULL,
 EMAIL VARCHAR(100),
 IS_ACTIVE BOOLEAN DEFAULT TRUE,
 CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_CLIENT_BANK
FOREIGN KEY (BANK_ID)
REFERENCES BANK(BANK_ID)
ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID BIGINT UNSIGNED NOT NULL,
    BANK_ID BIGINT UNSIGNED NOT NULL,
    BALANCE DECIMAL(15,2) DEFAULT 0,
    IS_BLOCKED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCOUNT_CLIENT
	FOREIGN KEY (CLIENT_ID)
	REFERENCES CLIENT(CLIENT_ID)
	ON DELETE CASCADE,
    CONSTRAINT FK_ACCOUNT_BANK
	FOREIGN KEY (BANK_ID)
	REFERENCES BANK(BANK_ID)
	ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE FUND_CATEGORY (
    FUND_CATEGORY_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255)
) ENGINE=INNODB;

CREATE TABLE FUND (
    FUND_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FUND_CATEGORY_ID BIGINT UNSIGNED NOT NULL,
    BANK_ID BIGINT UNSIGNED NOT NULL,
    FUND_NAME VARCHAR(100) NOT NULL,
    RISK_LEVEL INT,
    MINIMUM_INVESTMENT DECIMAL(15,2),
    IS_OPEN BOOLEAN DEFAULT TRUE,
    CONSTRAINT FK_FUND_CATEGORY
	FOREIGN KEY (FUND_CATEGORY_ID)
	REFERENCES FUND_CATEGORY(FUND_CATEGORY_ID)
	ON DELETE CASCADE,
    CONSTRAINT FK_FUND_BANK
	FOREIGN KEY (BANK_ID)
	REFERENCES BANK(BANK_ID)
	ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID BIGINT UNSIGNED NOT NULL,
    ACCOUNT_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PORTFOLIO_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT(CLIENT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PORTFOLIO_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID)
        ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE PORTFOLIO_FUND (
    PORTFOLIO_FUND_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PORTFOLIO_ID BIGINT UNSIGNED NOT NULL,
    FUND_ID BIGINT UNSIGNED NOT NULL,
    INVESTED_AMOUNT DECIMAL(15,2),
    CONSTRAINT FK_PF_PORTFOLIO
        FOREIGN KEY (PORTFOLIO_ID)
        REFERENCES PORTFOLIO(PORTFOLIO_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PF_FUND
        FOREIGN KEY (FUND_ID)
        REFERENCES FUND(FUND_ID)
        ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE TRANSACTION (
    TRANSACTION_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT UNSIGNED NOT NULL,
    FUND_ID BIGINT UNSIGNED,
    AMOUNT DECIMAL(15,2),
    TRANSACTION_TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRANSACTION_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_TRANSACTION_FUND
        FOREIGN KEY (FUND_ID)
        REFERENCES FUND(FUND_ID)
        ON DELETE CASCADE
) ENGINE=INNODB;

INSERT INTO BANK (BANK_NAME, COUNTRY)
VALUES ('BANCO NATIONS', 'BRASIL'),
       ('BANCO TOKYO', 'JAPAN');
       
INSERT INTO CLIENT (BANK_ID, CLIENT_NAME, EMAIL)
VALUES (1, 'JOÃO VICTOR', 'JOÃO@email.com'),
       (1, 'MARIA J SOUZA', 'JMARIA@email.com');

INSERT INTO ACCOUNT (CLIENT_ID, BANK_ID, BALANCE)
VALUES (1, 1, 5000),
       (2, 1, 8000);
       
INSERT INTO FUND_CATEGORY (CATEGORY_NAME, DESCRIPTION)
VALUES ('RENDA FIXA', 'BAIXO RISCO'),
       ('AÇÕES', 'ALTO RISCO');
       
     
INSERT INTO FUND (FUND_CATEGORY_ID, BANK_ID, FUND_NAME, 
RISK_LEVEL, MINIMUM_INVESTMENT) 
VALUES (1, 1, 'FUNDO CONSERVADOR', 1, 1000), 
(2, 1, 'FUNDO AGRESSIVO', 5, 5000);

INSERT INTO FUND (FUND_CATEGORY_ID, BANK_ID, FUND_NAME, RISK_LEVEL, 
MINIMUM_INVESTMENT)
VALUES (1, 1, 'GLOBAL EQUITY FUND', 5, 1000);

INSERT INTO PORTFOLIO (CLIENT_ID, ACCOUNT_ID)
VALUES (1, 5);

INSERT INTO PORTFOLIO_FUND (PORTFOLIO_ID, FUND_ID, 
INVESTED_AMOUNT)
VALUES (4, 1, 5);

INSERT INTO TRANSACTION (ACCOUNT_ID, FUND_ID, AMOUNT, 
TRANSACTION_TYPE)
VALUES (5, 1, 10000, 'APLICACAO');

SELECT ACCOUNT_ID, CLIENT_ID, BANK_ID FROM ACCOUNT;

UPDATE ACCOUNTSET IS_BLOCKED = TRUEWHERE account_id = 1
  AND balance > 0;
 
 SET SQL_SAFE_UPDATES = 0;

  
UPDATE ACCOUNT
SET IS_BLOCKED = 1
WHERE BALANCE < 1000
AND IS_BLOCKED = 0;

UPDATE FUND
SET IS_ACTIVE = 0
WHERE RISK_LEVEL > 4
  AND IS_ACTIVE = 1;

ALTER TABLE ACCOUNT
ADD COLUMN UPDATED_AT
TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ON UPDATE CURRENT_TIMESTAMP;

BEGIN;
UPDATE ACCOUNT
SET BALANCE = BALANCE - 1000
WHERE ACCOUNT_ID = 1;
ROLLBACK;

DELETE FROM TRANSACTION
WHERE AMOUNT > 5000
OR TRANSACTION_TYPE = 'SAQUE';
   
TRUNCATE TABLE PORTFOLIO_FUND CASCADE;

SET @n := 0;
INSERT INTO CLIENT (BANK_ID, CLIENT_NAME, EMAIL)
SELECT
  1,
  CONCAT('Cliente ', @n := @n + 1),
  CONCAT('cliente', @n, '@email.com')
FROM INFORMATION_SCHEMA.TABLES
LIMIT 1000;

SELECT *FROM FUND WHERE MINIMUM_INVESTMENT > 1000
  AND IS_OPEN = TRUEORDER BY RISK_LEVEL DESC;

SELECT *FROM CLIENT WHERE CLIENT_NAME 
LIKE 'M%'ORDER BY CLIENT_NAME ASC;

SELECT *FROM ACCOUNT WHERE ACCOUNT_ID IN (1,2,3)
  AND IS_BLOCKED = FALSE;
  
  SELECT *FROM TRANSACTION WHERE AMOUNT < 3000
   OR TRANSACTION_TYPE = 'APLICACAO'ORDER BY CREATED_AT DESC;
      
       
       