USE DB_JOAO_VICTOR;

CREATE TABLE CATEGORIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE FOODS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

INSERT INTO CATEGORIES (NAME) VALUES
('FAST FOOD'),
('SNACK'),
('DRINK'),
('VEGETARIAN'),
('ITALIAN FOOD'),
('JAPANESE FOOD'),
('MEXICAN FOOD'),
('BREAKFAST'),
('SEAFOOD'),
('DESSERT');

INSERT INTO FOODS (NAME, PRICE, CATEGORY_ID) VALUES
('HAMBURGER', 25.00, 1),
('PIZZA', 40.00, 1),
('CHEESECAKE', 18.00, 2),
('ICE CREAM', 12.00, 2),
('COKE', 6.00, 3),
('ORANGE JUICE', 8.00, 3),
('VEGGIE BURGER', 22.00, 4),
('PASTA', 35.00, 5),
('SUSHI', 50.00, 6),
('TACO', 15.00, 7);

SELECT FOODS.NAME AS FOOD,
FOODS.PRICE,
CATEGORIES.NAME AS CATEGORY
FROM FOODS
JOIN  CATEGORIES ON FOODS.CATEGORY_ID = CATEGORIES.ID;

SELECT FOODS.NAME, FOODS.price
FROM FOODS
JOIN CATEGORIES ON FOODS.CATEGORY_ID = CATEGORIES.ID
WHERE CATEGORIES.NAME = 'FAST FOOD';

SELECT * FROM FOODS
ORDER BY PRICE DESC;

DELETE FROM FOODS
WHERE NAME = 'COKE';

DELETE FROM FOODS
WHERE PRICE < 10;

SELECT * FROM FOODS;


