USE DB_JOAO_VICTOR;

CREATE TABLE CATEGORIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE FOODS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

INSERT INTO CATEGORIES (NAME) VALUES
('FAST FOOD'),
('SNACK'),
('DRINK'),
('VEGETARIAN'),
('ITALIAN FOOD'),
('JAPANESE FOOD'),
('MEXICAN FOOD'),
('BREAKFAST'),
('SEAFOOD'),
('DESSERT');

INSERT INTO FOODS (NAME, PRICE, CATEGORY_ID) VALUES
('HAMBURGER', 25.00, 1),
('PIZZA', 40.00, 1),
('CHEESECAKE', 18.00, 2),
('ICE CREAM', 12.00, 2),
('COKE', 6.00, 3),
('ORANGE JUICE', 8.00, 3),
('VEGGIE BURGER', 22.00, 4),
('PASTA', 35.00, 5),
('SUSHI', 50.00, 6),
('TACO', 15.00, 7);

SELECT FOODS.NAME AS FOOD,
FOODS.PRICE,
CATEGORIES.NAME AS CATEGORY
FROM FOODS
JOIN  CATEGORIES ON FOODS.CATEGORY_ID = CATEGORIES.ID;

SELECT FOODS.NAME, FOODS.price
FROM FOODS
JOIN CATEGORIES ON FOODS.CATEGORY_ID = CATEGORIES.ID
WHERE CATEGORIES.NAME = 'FAST FOOD';

SELECT * FROM FOODS
ORDER BY PRICE DESC;

DELETE FROM FOODS
WHERE NAME = 'COKE';

SET SQL_SAFE_UPDATES = 0;

DELETE FROM FOODS
WHERE PRICE < 10;

SELECT * FROM FOODS;

SELECT NAME, PRICE
FROM FOODS
WHERE PRICE BETWEEN 16 AND 39
AND PRICE < 40
AND CATEGORY_ID = 'FAST FOOD'
AND NAME LIKE '%A%'
ORDER BY PRICE DESC;

SELECT name, price
FROM foods
WHERE price > 15
  AND price < 40
  AND category = 'FAST FOOD'
  AND name LIKE '%A%'
ORDER BY price DESC;