
SELECT
    P.NAME,
    P.PRICE,
    R.RANGE_NAME AS PRICE_CATEGORY
FROM PRODUCTS P
INNER JOIN PRICE_RANGES R
    ON P.PRICE BETWEEN R.PRICE_MIN AND R.PRICE_MAX;
    
    SELECT
    P.NAME,
    P.PRICE,
    R.RANGE_NAME AS PRICE_CATEGORY
FROM PRODUCTS P
INNER JOIN PRICE_RANGES R
    ON P.PRICE >= R.PRICE_MIN AND P.PRICE < R.PRICE_MAX;
    
    SELECT
    P.NAME,
    P.PRICE,
    R.RANGE_NAME AS PRICE_CATEGORY
FROM PRODUCTS P
INNER JOIN PRICE_RANGES R
    ON P.PRICE >= R.PRICE_MIN
   AND P.PRICE < R.PRICE_MAX;
   
   SELECT
    P.NAME,
    P.PRICE,
    R.RANGE_NAME AS PRICE_CATEGORY
FROM PRODUCTS P
INNER JOIN PRICE_RANGES R
    ON P.PRICE >= R.PRICE_MIN
   AND P.PRICE <= R.PRICE_MAX;
