USE DB_JOAO_VICTOR;

SELECT 
    P.NOME_PRODUTO,
    F.NOME_FORNECEDOR
FROM PRODUTOS P
INNER JOIN FORNECEDORES F
    ON P.ID_FORNECEDOR = F.ID_FORNECEDOR;
    
    SELECT
    P.NOME_PRODUTO,
    IV.QUANTIDADE,
    V.DATA_VENDA
FROM ITENS_VENDA IV
INNER JOIN PRODUTOS P
    ON IV.ID_PRODUTO = P.ID_PRODUTO
INNER JOIN VENDAS V
    ON IV.ID_VENDA = V.ID_VENDA;
    
    SELECT
    P.NOME_PRODUTO,
    (IV.QUANTIDADE * IV.VALOR_UNITARIO) AS VALOR_TOTAL_VENDA,
    F.NOME_FORNECEDOR
FROM ITENS_VENDA IV
INNER JOIN PRODUTOS P
    ON IV.ID_PRODUTO = P.ID_PRODUTO
INNER JOIN FORNECEDORES F
    ON P.ID_FORNECEDOR = F.ID_FORNECEDOR;
    
    SELECT
    P.NOME_PRODUTO,
    P.ESTOQUE,
    F.NOME_FORNECEDOR
FROM PRODUTOS P
INNER JOIN FORNECEDORES F
    ON P.ID_FORNECEDOR = F.ID_FORNECEDOR
WHERE P.ESTOQUE < 30;