CREATE DATABASE RH_DB_JOAO_VICTOR;

USE RH_DB_JOAO_VICTOR;

CREATE TABLE DEPARTAMENTOS (
    ID_DEPTO INT PRIMARY KEY,
    NOME_DEPTO VARCHAR(50)
);

CREATE TABLE NIVEIS_SALARIAIS (
    NIVEL VARCHAR(20) PRIMARY KEY,
    SALARIO_MIN DECIMAL(10,2),
    SALARIO_MAX DECIMAL(10,2)
);

CREATE TABLE FUNCIONARIOS (
    ID_FUNC INT PRIMARY KEY,
    NOME VARCHAR(100),
    SALARIO DECIMAL(10,2),
    ID_DEPTO INT,
    FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTOS(ID_DEPTO)
);

INSERT INTO DEPARTAMENTOS VALUES
(1, 'VENDAS'),
(2, 'TI'),
(3, 'INOVACAO');

INSERT INTO NIVEIS_SALARIAIS VALUES
('JUNIOR', 3000, 5000),
('PLENO', 5001, 9000),
('SENIOR', 9001, 15000);

INSERT INTO FUNCIONARIOS VALUES
(1, 'ANA', 4500, 1),
(2, 'BETO', 8200, 1),
(3, 'CLARA', 12500, 2);

SELECT
    D.NOME_DEPTO AS DEPARTAMENTO,
    F.NOME AS FUNCIONARIO
FROM DEPARTAMENTOS D
LEFT JOIN FUNCIONARIOS F
    ON F.ID_DEPTO = D.ID_DEPTO;
    
    SELECT
    F.NOME,
    F.SALARIO,
    N.NIVEL
FROM FUNCIONARIOS F
INNER JOIN NIVEIS_SALARIAIS N
    ON F.SALARIO BETWEEN N.SALARIO_MIN AND N.SALARIO_MAX;
    
    SELECT
    F.NOME AS FUNCIONARIO
FROM FUNCIONARIOS F
INNER JOIN DEPARTAMENTOS D
    ON D.ID_DEPTO = F.ID_DEPTO
INNER JOIN NIVEIS_SALARIAIS N
    ON F.SALARIO BETWEEN N.SALARIO_MIN AND N.SALARIO_MAX
WHERE N.NIVEL = 'PLENO'
  AND D.NOME_DEPTO = 'VENDAS';
