USE DB_JOAO_VICTOR;

CREATE TABLE TEACHERS ( 
ID INT PRIMARY KEY AUTO_INCREMENT, 
NAME VARCHAR(100) NOT NULL, 
SUBJECT VARCHAR(50) NOT NULL );

CREATE TABLE CLASSES ( 
ID INT PRIMARY KEY AUTO_INCREMENT, 
CLASS_NAME VARCHAR(50) NOT NULL, 
TEACHER_ID INT, FOREIGN KEY (TEACHER_ID) 
REFERENCES TEACHERS(ID) ); 

CREATE TABLE STUDENTS ( 
ID INT PRIMARY KEY AUTO_INCREMENT, 
NAME VARCHAR(100) NOT NULL, 
AGE INT NOT NULL, CLASS_ID INT,
 FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) );
 
 CREATE TABLE GRADES (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 STUDENT_ID INT, GRADE DECIMAL(4,2), 
 FOREIGN KEY (STUDENT_ID) 
REFERENCES STUDENTS(ID) );

INSERT INTO TEACHERS (NAME, SUBJECT) 
VALUES ('Carlos Silva', 'Math'), ('Ana Souza', 'Portuguese'), 
('Marcos Lima', 'History'), ('Juliana Rocha', 'Geography'); 

INSERT INTO CLASSES (CLASS_NAME, TEACHER_ID) 
VALUES 
('1A', 1), ('1B', 2), ('2A', 1), ('2B', 3), ('3A', 4);

INSERT INTO STUDENTS (NAME, AGE, CLASS_ID) 
VALUES ('John', 15, 1), ('Mary', 14, 1), ('Peter', 15, 1), 
('Anna', 14, 2), ('Lucas', 16, 2), ('Fernanda', 15, 2), ('Rafael', 16, 3),
 ('Beatriz', 15, 3), ('Camila', 16, 4),
 ('Bruno', 17, 4), ('Daniel', 17, 5), ('Larissa', 16, 5);
 
 INSERT INTO GRADES (STUDENT_ID, GRADE) 
 VALUES (1, 8.0), (1, 7.5), (2, 9.0), (2, 8.5), (3, 6.0), (4, 7.0), 
 (4, 6.5), (5, 8.0), (6, 9.5), (7, 5.5), (8, 7.5),
 (9, 6.0), (10, 8.0), (11, 9.0), (12, 7.0);
 
 SELECT 
    S.NAME AS ALUNO,
    C.CLASS_NAME AS TURMA,
    T.NAME AS PROFESSOR,
    T.SUBJECT AS DISCIPLINA
FROM STUDENTS S
JOIN CLASSES C ON S.CLASS_ID = C.ID
JOIN TEACHERS T ON C.TEACHER_ID = T.ID;

SELECT
    S.NAME AS ALUNO,
    G.GRADE AS NOTA,
    T.SUBJECT AS DISCIPLINA
FROM GRADES G
JOIN STUDENTS S ON G.STUDENT_ID = S.ID
JOIN CLASSES C ON S.CLASS_ID = C.ID
JOIN TEACHERS T ON C.TEACHER_ID = T.ID;

SELECT
    S.NAME AS ALUNO,
    G.GRADE AS NOTA
FROM STUDENTS S
LEFT JOIN GRADES G ON S.ID = G.STUDENT_ID;

SELECT
    S.NAME,
    S.AGE
FROM STUDENTS S
JOIN GRADES G ON S.ID = G.STUDENT_ID
GROUP BY S.ID, S.NAME, S.AGE
HAVING AVG(G.GRADE) > (
    SELECT AVG(GRADE)
    FROM GRADES
);

SELECT
    S.NAME AS ALUNO,
    AVG(G.GRADE) AS MEDIA
FROM STUDENTS S
JOIN GRADES G ON S.ID = G.STUDENT_ID
WHERE S.CLASS_ID IN (
    SELECT C.ID
    FROM CLASSES C
    JOIN TEACHERS T ON C.TEACHER_ID = T.ID
    WHERE T.NAME = 'CARLOS SILVA'
)
GROUP BY S.ID, S.NAME;

SELECT
    C.CLASS_NAME,
    COUNT(S.ID) AS TOTAL_ALUNOS
FROM CLASSES C
JOIN STUDENTS S ON C.ID = S.CLASS_ID
GROUP BY C.ID, C.CLASS_NAME
HAVING COUNT(S.ID) > (
    SELECT AVG(QTD)
    FROM (
        SELECT COUNT(*) AS QTD
        FROM STUDENTS
        GROUP BY CLASS_ID
    ) AS MEDIA_TURMAS
);