USE GAME_PLATFORM;

SELECT TITLE, PRICE
FROM GAMES
WHERE PRICE > (SELECT AVG(PRICE)
FROM GAMES);

SELECT NAME
FROM USERS
WHERE ID IN (SELECT USER_ID
FROM PURCHASES);

SELECT DISTINCT U.NAME
FROM USERS U
JOIN PURCHASES P ON P.USER_ID = U.ID;

SELECT DISTINCT G.TITLE
FROM GAMES G
JOIN REVIEWS R ON R.GAME_ID = G.ID;

SELECT DISTINCT G.TITLE, G.PRICE
FROM GAMES G
JOIN PURCHASES P ON P.GAME_ID = G.ID
WHERE G.PRICE > (SELECT AVG(PRICE)
FROM GAMES);

SELECT U.NAME
FROM USERS U
LEFT JOIN PURCHASES P ON P.USER_ID = U.ID
WHERE P.ID IS NULL;

SELECT NAME
FROM USERS
WHERE ID NOT IN (SELECT USER_ID
FROM PURCHASES);

SELECT G.TITLE, AVG(R.SCORE) AS MEDIA_SCORE
FROM GAMES G
JOIN REVIEWS R ON R.GAME_ID = G.ID
GROUP BY G.TITLE
HAVING AVG(R.SCORE) > 4;

SELECT G.TITLE
FROM GAMES G
JOIN REVIEWS R ON R.GAME_ID = G.ID
GROUP BY G.TITLE
HAVING COUNT(R.ID) > (SELECT AVG(QTD)
FROM (SELECT COUNT(*) AS QTD
FROM REVIEWS
GROUP BY GAME_ID) SUB);

SELECT DISTINCT U.NAME
FROM USERS U
JOIN REVIEWS R ON R.USER_ID = U.ID
WHERE R.SCORE < (SELECT AVG(SCORE)
FROM REVIEWS);

SELECT TITLE, PRICE
FROM GAMES
WHERE PRICE > ALL (SELECT PRICE
FROM GAMES
WHERE GENRE = 'ACTION');

SELECT U.NAME, SUM(G.PRICE) AS TOTAL_GASTO
FROM USERS U
JOIN PURCHASES P ON P.USER_ID = U.ID
JOIN GAMES G ON G.ID = P.GAME_ID
GROUP BY U.NAME
HAVING SUM(G.PRICE) > (
SELECT AVG(TOTAL)
FROM (SELECT SUM(G2.PRICE) AS TOTAL
FROM PURCHASES P2
JOIN GAMES G2 ON G2.ID = P2.GAME_ID
GROUP BY P2.USER_ID) SUB);

SELECT G.TITLE
FROM GAMES G
WHERE NOT EXISTS (SELECT 1
FROM USERS U
WHERE U.COUNTRY = 'BRAZIL'
AND NOT EXISTS (SELECT 1
FROM PURCHASES P
WHERE P.USER_ID = U.ID
AND P.GAME_ID = G.ID));

SELECT U.NAME
FROM USERS U
JOIN PURCHASES P ON P.USER_ID = U.ID
JOIN GAMES G ON G.ID = P.GAME_ID
WHERE G.PRICE > (SELECT AVG(PRICE)
FROM GAMES)
GROUP BY U.ID, U.NAME
HAVING COUNT(DISTINCT G.ID) = (SELECT COUNT(*)
FROM GAMES
WHERE PRICE > (
SELECT AVG(PRICE)
FROM GAMES));

















                             
                   
                   