USE DB_JOAO_VICTOR;

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    BIRTH_DATE DATE,
    IS_PREMIUM BOOLEAN,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ARTISTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    COUNTRY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GENRES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ALBUMS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100),
    RELEASE_YEAR INT,
    ARTIST_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTISTS(ID)
        ON DELETE SET NULL
);

CREATE TABLE SONGS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100),
    DURATION_SECONDS INT,
    ALBUM_ID INT,
    GENRE_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ALBUM_ID)
        REFERENCES ALBUMS(ID)
        ON DELETE SET NULL,
    FOREIGN KEY (GENRE_ID)
        REFERENCES GENRES(ID)
        ON DELETE SET NULL
);

CREATE TABLE PLAYLISTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    USER_ID INT,
    IS_PUBLIC BOOLEAN,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
        ON DELETE SET NULL
);

CREATE TABLE PLAYLIST_SONGS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PLAYLIST_ID INT,
    SONG_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PLAYLIST_ID)
        REFERENCES PLAYLISTS(ID)
        ON DELETE SET NULL,
    FOREIGN KEY (SONG_ID)
        REFERENCES SONGS(ID)
        ON DELETE SET NULL
);

CREATE TABLE PLAYS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    SONG_ID INT,
    PLAY_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
        ON DELETE SET NULL,
    FOREIGN KEY (SONG_ID)
        REFERENCES SONGS(ID)
        ON DELETE SET NULL
);

CREATE TABLE SONG_REVIEWS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    SONG_ID INT,
    RATING INT,
    REVIEW_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
        ON DELETE SET NULL,
    FOREIGN KEY (SONG_ID)
        REFERENCES SONGS(ID)
        ON DELETE SET NULL
);

CREATE TABLE ARTIST_FOLLOWERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ARTIST_ID INT,
    FOLLOW_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
        ON DELETE SET NULL,
    FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTISTS(ID)
        ON DELETE SET NULL
);

INSERT INTO USERS (NAME, EMAIL, BIRTH_DATE, IS_PREMIUM) VALUES
('ANA','ANA@EMAIL.COM','1999-05-10',TRUE),
('BRUNO','BRUNO@EMAIL.COM','2002-08-20',FALSE),
('CARLOS','CARLOS@EMAIL.COM','1995-01-15',TRUE),
('DANIELA','DANI@EMAIL.COM','2001-03-22',FALSE),
('EDUARDO','EDU@EMAIL.COM','1990-11-02',TRUE);

INSERT INTO ARTISTS (NAME, COUNTRY) VALUES
('COLDPLAY','UK'),
('DRAKE','CANADA'),
('SEPULTURA','BRAZIL'),
('TAYLOR SWIFT','USA'),
('ALCIONE','BRAZIL'),
('FLAVIO JOSE','BRAZIL');

INSERT INTO GENRES (NAME) VALUES
('POP'),('ROCK'),('HIP HOP'),('SAMBA'),('FORRO');

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID) VALUES
('PARACHUTES',2000,1),
('SCORPION',2018,2),
('VERSIONS OF ME',2022,3),
('1989',2014,4),
('MAP OF THE SOUL',2020,5);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID, GENRE_ID)
SELECT CONCAT('SONG ', N), 180 + (N * 2), (N % 5) + 1, (N % 5) + 1
FROM (
    SELECT 1 N UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
) X;

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC) VALUES
('TREINO',1,TRUE),
('CHILL',2,FALSE),
('HITS',3,TRUE);

INSERT INTO PLAYLIST_SONGS (PLAYLIST_ID, SONG_ID) VALUES
(1,1),(1,2),(1,3),(2,4),(2,5),(3,6),(3,7),(3,8);

INSERT INTO PLAYS (USER_ID, SONG_ID, PLAY_DATE)
SELECT 1, ID, CURDATE() - INTERVAL ID DAY FROM SONGS LIMIT 20;

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING, REVIEW_DATE) VALUES
(1,1,5,CURDATE()),
(2,2,3,CURDATE()),
(3,3,2,CURDATE()),
(4,4,4,CURDATE()),
(5,5,1,CURDATE());

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID, FOLLOW_DATE) VALUES
(1,1,CURDATE()),
(2,1,CURDATE()),
(3,2,CURDATE()),
(4,2,CURDATE()),
(5,3,CURDATE());

SELECT * FROM SONGS WHERE DURATION_SECONDS > 220;

SELECT * FROM SONGS WHERE GENRE_ID IN (1,3);

SELECT * FROM PLAYLISTS WHERE IS_PUBLIC = TRUE;

SELECT * FROM SONGS WHERE TITLE LIKE '%SONG%';

SELECT * FROM SONGS ORDER BY DURATION_SECONDS DESC;

SELECT S.TITLE, A.NAME
FROM SONGS S
JOIN ALBUMS AL ON S.ALBUM_ID = AL.ID
JOIN ARTISTS A ON AL.ARTIST_ID = A.ID;

SELECT P.NAME, U.NAME
FROM PLAYLISTS P
JOIN USERS U ON P.USER_ID = U.ID;

SELECT S.TITLE, G.NAME
FROM SONGS S
JOIN GENRES G ON S.GENRE_ID = G.ID;

SELECT DISTINCT U.NAME
FROM USERS U
JOIN ARTIST_FOLLOWERS AF ON U.ID = AF.USER_ID
WHERE U.IS_PREMIUM = TRUE;

SELECT U.NAME, S.TITLE, P.PLAY_DATE
FROM PLAYS P
JOIN USERS U ON P.USER_ID = U.ID
JOIN SONGS S ON P.SONG_ID = S.ID;


SELECT DISTINCT S.TITLE
FROM SONGS S
LEFT JOIN SONG_REVIEWS R ON S.ID = R.SONG_ID
WHERE S.DURATION_SECONDS > 240 OR R.RATING < 3;










